spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: prasad
    url: jdbc:postgresql://localhost:5432/testing_db_01
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.username}
#    schemas: public


